---
title: "First PCAs on emissions and preferences"
author: "Martin blasi"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load the data
```{r}
load("C:/Users/blasi/OneDrive/Desktop/UPF Studies/multivariate data analysis/Class/Group project/1 LOCAL COPIES/gps/Emissions_and_Preferences.RData")
```
Summary statistics
```{r}
summary(df.empref)
```

Subset
```{r}
library("dplyr")
df.empref1 =
  df.empref %>%
    select(-c(country))

rownames(df.empref1) <- df.empref1[,1]

df.empref2 =
  df.empref1 %>%
    select(-c(iso_code))
```
Scale and covariance matrix
```{r}
X <- as.matrix(df.empref2)

Xs <- scale(X)
R <- cov(Xs)
```
PCA
```{r}
l <- eigen(R)$values
V <- eigen(R)$vectors
Y <- Xs %*% V
# the portion of the variance that retains each PC
R2 = l / sum(l) *100
# accumulating this quantities:
cumsum( l / sum(l))

#automatically
library(ade4)
library(factoextra)
pca.empref = dudi.pca(df.empref2, scannf = FALSE)
pca.empref$eig
cumsum(pca.empref$eig)/sum(pca.empref$eig)
fviz_eig(pca.empref, geom = "bar", bar_width = 0.3, addlabels=T) + ggtitle("")
```

```{r}
#Plot
plot(Y[,1:2],
  type="n", # don't plot anything now
  asp = 1, # aspect ratio, very important!
  main=paste("Variables plot, expl. var is ",
               round(R2[1]+R2[2],1), " %"),
  xlab=paste("CP1(", round(R2[1],1), "%)"), # title x axis
  ylab=paste("CP2(", round(R2[2],1), "%)") # title y axis
)

# add the axis
abline(v=0, col="blue")
abline(h=0, col="blue")

# the dots and names
points(Y[,1:2], pch=".") # plot a dot per row
text(Y[,1:2],row.names(df.empref2),cex=0.6)
```

SVD and Variables Plot
```{r}
#Carry out the Singular Value Decomposition
svd <- svd(Xs)


Utilde <- svd$u[,1:2] %*% sqrt(diag(svd$d[1:2]))
Vtilde <- svd$v[,1:2] %*% sqrt(diag(svd$d[1:2]))


nn <- paste(rownames(Xs))
xlim <- ylim <- range(c(range(Vtilde)))
plot(NULL,xlab='First biplot component',ylab='Second biplot component',xlim=xlim,ylim=ylim,cex.lab=1.25)
arrows(x0=0,y0=0,x1=Vtilde[,1],y1=Vtilde[,2],col='red')
text(.9*Vtilde[,1],Vtilde[,2],paste(colnames(Xs)),pos=c(1,3),col='red',cex=1.25)
```
Biplot
```{r}
nn <- paste(rownames(Xs))
xlim <- ylim <- range(c(range(Vtilde),range(Utilde)))
plot(Utilde,xlab='First biplot component',ylab='Second biplot component',xlim=xlim,ylim=ylim,cex.lab=1.25)
text(Utilde[,1:2],nn,pos=c(4,1,2),cex=1.25)
arrows(x0=0,y0=0,x1=Vtilde[,1],y1=Vtilde[,2],col='red')
text(.9*Vtilde[,1],Vtilde[,2],paste(colnames(Xs)),pos=c(1,3),col='red',cex=1.25)

```
Distances
```{r}
d_euclidean <- dist(Xs)
d_manhattan <- dist(Xs, method="manhattan")

# S^(-1/2)
Sinvsqrt = V%*%diag(1/sqrt(l))

# X in mahalanobis space
Xinvsqrt = Xs%*%Sinvsqrt

d_mahalanobis <- as.dist(dist(Xinvsqrt))
```
Hierarchical Clustering
Eucledian
```{r}
hc <- hclust(d_euclidean)
plot(hc ,hang = -1, main="Euclidean dist - Complete linkage")
```
Manhattan
```{r}
hc <- hclust(d_manhattan)
plot(hc ,hang = -1, main="Manhatta dist - Complete linkage")
```
Mahalanobis
```{r}
hc <- hclust(d_mahalanobis)
plot(hc ,hang = -1, main="Mahalanobis dist - Complete linkage")
```
Linkage
Complete
```{r}
hc <- hclust(d_manhattan)
plot(hc ,hang = -1, main="Manhattan dist - Complete linkage")
```
Single
```{r}
hc <- hclust(d_manhattan,method = "single")
plot(hc ,hang = -1, main="Manhatta dist - Single linkage")
```
Average
```{r}
hc <- hclust(d_manhattan,method="average")
plot(hc ,hang = -1, main="Manhatta dist - Average linkage")
```
k-means
```{r}
pc <- prcomp(Xs)$x
km1 <- kmeans(Xs, centers = 4 )
km2 <- kmeans(Xs, centers = 5 )
km3 <- kmeans(Xs, centers = 6 )
km4 <- kmeans(Xs, centers = 7 )
clus1 <- km1$cluster
clus2 <- km2$cluster
clus3 <- km3$cluster
clus4 <- km4$cluster
plot(pc[,1],pc[,2],col=clus1,pch=clus1,xlab='PC1',ylab='PC2',main="Plot with k-mean with k=4")
text(pc[,1]-0.1,pc[,2]-0.1, labels=rownames(X))
plot(pc[,1],pc[,2],col=clus2,pch=clus2,xlab='PC1',ylab='PC2',main="Plot with k-mean with k=5")
text(pc[,1]-0.1,pc[,2]-0.1, labels=rownames(X))
plot(pc[,1],pc[,2],col=clus3,pch=clus3,xlab='PC1',ylab='PC2',main="Plot with k-mean with k=6")
text(pc[,1]-0.1,pc[,2]-0.1, labels=rownames(X))
plot(pc[,1],pc[,2],col=clus4,pch=clus4,xlab='PC1',ylab='PC2',main="Plot with k-mean with k=7")
text(pc[,1]-0.1,pc[,2]-0.1, labels=rownames(X))
```
Choosing k formally
```{r}
wss = c(sum(Xs^2))

for (i in 2:10) {
  km  = kmeans(Xs, centers = i)
  wss = c(wss,sum(km$withinss))
}
plot(wss,xlab="k",ylab="wss",main="WSS-Euclidean")
```
=>k=5 seems reasonable
