---
title: "Climate Pledges"
author: "Jonas Wallstein"
date: "2022-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The goal is to create summary statistics for climate pledges of different countries. The data spans 66 Countries

```{r}
setwd('..')
getwd()
pledges = read.csv("Project/net-zero-targets.csv",sep = ",", header = TRUE)

summary(pledges$Year)
hist(pledges$Year, xlab = "Net-zero Goal", breaks = 20)

```












```{r}
## Old Data
# file = "/Users/jonaswallstein/Library/Mobile Documents/com~apple~CloudDocs/Upf/MDA/Project/lts_content/lts_content.csv"
# pledges = read.table(file, sep = ",", header = TRUE)
# 
# pledges$target2050  = c(100, 100, 100, 100, NA, 100, 80, 100, NA, 100, 100, 80, 100, 100, 100, NA, 100, 100, 80, 59, 100, NA, 
#                         NA, 100, 100, 100, 100, 72, 100, 100, 50, NA, NA, 95, 100, 50, 80, 100, 80, NA, 100, 100, NA, 100, 100, NA,
#                   100, NA, NA, 31, 100, 100, 100)
# head(pledges, 3)
# summary(pledges$target2050)
# hist(pledges$target2050, xlab = "Emission Reduction by 2050 in %")
````
